spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxx #数据库用户名
    password: xxx #数据库密码
    url: xxx #数据库地址
    #druid 数据源专有配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      keep-alive: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  redis:
    host: xxx #redis地址
    port: xxx #redis端口
    password: xxx #redis密码
    connect-timeout: 5000
    database: 0
  # 电子邮件发送配置
  mail:
    username: xxx #电子邮件发送邮箱
    password: xxx #邮箱的授权码
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: UTF-8
  thymeleaf:
    check-template-location: false
server:
  servlet:
    context-path: /api
  port: 8080
  #ssl证书配置
  ssl:
    key-store-type: xxx
    key-store: xxx
    key-store-password: xxx
#阿里云短信配置
aliyun:
  sms:
    accessKeyId: xxx
    accessKeySecret: xxx
    endpoint: xxx
    sMVCode:
      signName: 阿里云短信测试
      templateCode: SMS_154950909
      limitTime: 5
jasypt:
  encryptor:
    # 随便写的加密密钥
    password: xxx
    # 随便的一个盐，为了每次加密相同内容得到的密文都是一样的
    salt: xxx